sudo: required
addons:
  apt:
    update: true
    packages:
    - docker-ce
services:
- docker
script:
- export DOCKER_CLI_EXPERIMENTAL=enabled
- source utils.sh
- apache_arm_sha=$(get_manifest_sha "treehouses/apache:latest" "arm")
- echo $apache_arm_sha
- php-apache_arm_sha=$(get_manifest_sha "treehouses/php-apache:latest" "arm")
- echo $php-apache_arm_sha
- flag_arm=$(is_base "treehouses/apache@"$apache_arm_sha "treehouses/php-apache@"$php-apache_arm_sha)
- echo $flag_arm
- apache_amd64_sha=$(get_manifest_sha "treehouses/apache:latest" "amd64")
- echo $apache_amd64_sha
- php-apache_amd64_sha=$(get_manifest_sha "treehouses/php-apache:latest" "amd64")
- echo $php-apache_amd64_sha
- flag_amd64=$(is_base "treehouses/apache@"$apache_amd64_sha "treehouses/php-apache@"$php-apache_amd64_sha)
- echo $flag_amd64
- apache_arm64_sha=$(get_manifest_sha "treehouses/apache:latest" "arm64")
- echo $apache_arm64_sha
- php-apache_arm64_sha=$(get_manifest_sha "treehouses/php-apache:latest" "arm64")
- echo $php-apache_arm64_sha
- flag_arm64=$(is_base "treehouses/apache@"$apache_arm64_sha "treehouses/php-apache@"$php-apache_arm64_sha)
- echo $flag_arm64
- echo $DOCKERAPIKEY | docker login -u "sevenseas" --password-stdin
- docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
- build_image "treehouses/apache:latest" arm "treehouses/php-apache"
- build_image "treehouses/apache:latest" amd64 "treehouses/php-apache"
- build_image "treehouses/apache:latest" arm64 "treehouses/php-apache"
- flag=$(compare "treehouses/apache@"$apache_arm_sha "treehouses/php-apache@"$php-apache_arm_sha "treehouses/apache@"$apache_amd64_sha "treehouses/php-apache@"$php-apache_amd64_sha "treehouses/apache@"$apache_arm64_sha "treehouses/php-apache@"$php-apache_arm64_sha "treehouses/php-apache:latest" "treehouses/php-apache-tags:amd64")
- echo $flag
#- flag=false
before_deploy:
- deploy_image "treehouses/php-apache" arm
- deploy_image "treehouses/php-apache" amd64
- deploy_image "treehouses/php-apache" arm64
- timetag=$(date +%Y%m%d%H%M)
- echo $timetag
- tag1="latest"
- tag2=$timetag
- echo $tag2
- create_manifest treehouses/php-apache $tag1 $tag2 treehouses/php-apache-tags:amd64 treehouses/php-apache-tags:arm
  treehouses/php-apache-tags:arm64
- docker manifest inspect treehouses/php-apache:$tag1
- docker manifest inspect treehouses/php-apache:$tag2
deploy:
- provider: script
  script: docker manifest push treehouses/php-apache:$tag1; docker manifest push treehouses/php-apache:$tag2
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$flag = true"
env:
  global:
    - secure: XDVGfURPbIEXrctRcNV4PvJHsHh0gA/zNBhwm5eowW7W73iPZL97ionYiywbvpxkSl6o8EYBhuz2WOLJL3rzHzPH3cFRQ4adf52KhUgJwa03cR1mfQShsimwLH89PDRyu+trcPFQ2AO2x6iZGiaAgKgm9NhKnq912eii4P3NYlaeskjpUWd45Fuo8n1kYBeZapOJHFk+DtHYLbjoJ2q04kH9jvugpYQXTpCsLf8oMEX/2pU+jzjJOVLeWo9Jb8VE1vtIaA1JSOZeOQfhy7TgUH1DKU5E5hAMoIrBC1Fxkd+u9ro4qTGG2sZBsqAsjkjoH/lLq3vQj+eqy1+aGyyfzM5TK40LJvC4TV2V3MZsPzXB474T91wG1hwKs+Q/7GD6qFZNwsvd7qOFbitcruG/3zTDxtqtK0fRgDgLhS8WS3YsXM6JVa7JysTrgTeuGAvnzhw6UM6g3+H3LXAtPkuHv5opZ+6WJQ5i5/LoXeyP9CmEsj01PJJf+4KvjJDv3LWFi49RRq5jQk0sRSHmwhFgGFklLVJErKhlHHjRH3Lsg4sZhDMZaQlyJkGS/s2CeicgSTo+q2KnEzSTxmzS6vj0opeAY2ONydCTSQsRUDGL2lWP5zhthJi+7hlAwifNtrJ7xijMnnY3yssnMWGSyemlERC2XdxYWNsrJaWvQEnuTIE=
